### ISSUE TITLE
Possible bug in the code

### ISSUE THREAD

**Issue by GitHimanshuc** [leowerneck/SFcollapse1D#1]
There may be an issue in the following line https://github.com/leowerneck/SFcollapse1D/blob/18f35b1ff0e95a08b7d3a6d9ca729cb9779f3af8/src/evolution.cpp#L246 

```c++
const int J     = Nx0Total;
const real tmp0 = - phi_n[J] / r_ito_x0[J];

```
It seems like the size of phi_n is Nx0Total so J should be Nx0Total-1.

```c++
const int J     = Nx0Total - 1;
const real tmp0 = - phi_n[J] / r_ito_x0[J];

```

**Comment by leowerneck** [comment]
Indeed! Thank you very much for the notification. I have fixed the bug and pushed the changes to the repo. As pointed out in the commit message, most of our runs pushed the outer boundary out of causal contact with the center of the grid, which is why this was left unnoticed.
