### ISSUE TITLE
Running An Example

### ISSUE THREAD

**Issue by seanjohn11** [leowerneck/SFcollapse1D#3]
The /SFcollapse1D code is not configured initially with the correct macros to produce the gif shown in the readme.md with the provided input. This made it difficult to check that it was running correctly. The current code will lead to a collapse before t=1. I believe that the gif was created with macros set to GAUSSIAN_SHELL not the V2 one. Also the R0 set to 0 and DELTA set to 1 as in the documentation. Please correct me if I am wrong. Thanks.

**Comment by leowerneck** [comment]
Indeed, that was correct; I must've mistakenly changed the macros file at some point. I have fixed the `macros.hpp` file so that the correct example is set when the repo is cloned. Thanks for pointing that out!
